title: Help me keep this project open-source and free 
platforms:
  - name: GitHub Sponsors
    url: https://github.com/shanoov9/fastify-serve/sponsors
  - name: Ko-fi
    url: https://ko-fi.com/shanoovishwakarma
  - name: shanoovishwakarma
